version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres/data

  kick:
    build:
      context: .
      dockerfile: ./kick/Dockerfile
    ports:
      - "7222:7222"
    # NEW
    environment:
      - PEOPLE_URL=http://people:8000/view/all
      - LOGIN_URL=http://people:8000/view/login_kick
    depends_on:
      - people

  people:
    build:
      context: .
      dockerfile: ./people/Dockerfile
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mydatabase
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8000:8000"
    entrypoint: ["./entrypoint.sh"]
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]

volumes:
  postgres-data: