"""init

Revision ID: b551a76751e5
Revises: 
Create Date: 2024-03-11 14:13:03.260550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b551a76751e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_body'), 'people', ['body'], unique=False)
    op.create_index(op.f('ix_people_title'), 'people', ['title'], unique=False)
    op.create_index(op.f('ix_people_user_id'), 'people', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_people_user_id'), table_name='people')
    op.drop_index(op.f('ix_people_title'), table_name='people')
    op.drop_index(op.f('ix_people_body'), table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###
